---
micronaut:
    application:
        name: app-with-discovery
                
#Uncomment to set server port
#    server:
#        port: 8080

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
